version: 0.2

phases:
  build:
    commands:
      - docker build -t be:1.5 backend/ 
  post_build:
    commands:
      - docker login -u username -p password
      - docker tag be:1.5 username/be:1.5
      - docker push username/be:1.5

artifacts:
    files:
      - 'Dockerrun.aws.json'
    name: Version
