name: Dev deployment from Github to AWS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push API Image
        run: |
          docker build -t hasniawan8/be:action -f backend/Dockerfile backend/
          docker push hasniawan8/be:action
          
      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/elastic-beanstalk-deploy-action@v1
        with:
          region: us-west-2
          application-name: my-app-name
          environment-name: my-env-name
          version-label: hasiawan8/be:action
          wait-for-deployment: true
